[package]
name = "auto-delete-email-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
native-tls = "0.2.10"
imap = "2.4.1"
